### ISSUE TITLE
Unable to use wifi in Harmony v3

### ISSUE THREAD

**Issue by karanbanthia** [Microchip-MPLAB-Harmony/net#1]
Hi,
I just got started with PIC32MZ curiosity development board with MRF24WN0MA Wi-Fi Module and MPLAB Harmony v3. I am unable to find drivers for wi-fi module (including ATWIN1500c) in harmony v3. Attached is an image of driver layer options which only includes Ethernet support. Harmony v2 used to support wi-fi. How do I use Wi-fi in Harmony v3 ?

![image](https://user-images.githubusercontent.com/11822967/60683645-812da700-9eb6-11e9-90bf-be816ae71d4c.png)

**Comment by adrian-aur** [comment]
Harmony 3 does not yet support the Wi-Fi modules. Until support is added you need to use Harmony 2.
