### ISSUE TITLE
Webserver issues

### ISSUE THREAD

**Issue by asyzen** [Microchip-MPLAB-Harmony/net#10]
We have some issues since the release of MPLAB 5.3 with Harmony3 
We compiled several times the example project web_net_server_nvm_mpfs, on multiple systems
Despite these attempts we cannot get the webserver up and running
We have a correct IP lease and ping works. Debug console does not show any runtime error
Any suggestions on what silent errors could have prevented the webserver from powering on ?
Thank you!

**Comment by adrian-aur** [comment]
Few things that come to mind that need to be checked:
- SYS_FS properly mounted
- The application registers the HTTP processing functions with the HTTP_NET
- The HTTP_NET is configured with the proper directory for the web pages on the mounted volume. This is what changed from the previous version: the application selects the SYS_FS mount point and the HTTP needs to be configured properly.

**Comment by adrian-aur** [comment]
No more feedback received.
