### ISSUE TITLE
tcpip_tcp_client problem on PIC32MX

### ISSUE THREAD

**Issue by ronnytittoto** [Microchip-MPLAB-Harmony/net#15]
net/apps/tcpip_tcp_client/firmware/pic32mx_eth_sk2.X/ does not open a com port on a PIC32 Ethernet Starter Kit II based on PIC32MX, the project does not start as expected and does not behave like the one on Harmony v2.06

**Comment by adrian-aur** [comment]
Is this issue about the console service? Please try to configure the project using MHC to open a console on the UART port and see if this fixes the issue.

**Comment by adrian-aur** [comment]
No more feedback received.
