### ISSUE TITLE
FTP Authorization

### ISSUE THREAD

**Issue by youpko** [Microchip-MPLAB-Harmony/net#18]
An update or two ago the Telnet server changed it authorization method to a callback method instead of static defined strings for user name and password. I would like to request the same approach for the FTP server module.

The core module also updated recently and it changed the filesystem dependency type in the harmony configuration so some links are missing in my configuration overview.

**Comment by adrian-aur** [comment]
Thank you for the good suggestion, we'll add it to the FTP server in a future release.
There will be a new release coming for net fairly soon, and it will use the latest versions from the core repo.  I hope your problems will be solved then.

**Comment by adrian-aur** [comment]
The FTP authentication has been updated and will be part of the 3.6.0 release.

**Comment by adrian-aur** [comment]
Solved in net 3.6.0
