### ISSUE TITLE
LAN9303 support seems incomplete

### ISSUE THREAD

**Issue by harkwoodservices** [Microchip-MPLAB-Harmony/net#24]
I can see various source files for the LAN9303 within the net ethphy files, but it doesn't seem to be complete.  It doesn't show up in MHC and looking at the various config files details for it are in some but not others.

Is the LAN9303 available as it was in Harmony v2 ?

I'm looking to refresh a project written using Harmony2, everything seems to be there apart from the LAN9303 support.

**Comment by adrian-aur** [comment]
MHC support for LAN9303 will be added in the coming net release, available in few weeks from now.

**Comment by harkwoodservices** [comment]
Excellent, thanks.  That should give me time to get to grips with it before attacking the migration in earnest.
