### ISSUE TITLE
ICMP Echo Responses Ignore Routing Table

### ISSUE THREAD

**Issue by DavidIngraham** [Microchip-MPLAB-Harmony/net#28]
In the ICMP driver, echo responses always reply directly to the SRC MAC of the echo request packet. ICMP is a layer 3 protocol and should use appropriate IP routing rules when sending responses.

This is particularly problematic on subnets which use asymmetric routes for ingress and egress. If incoming packets come in from one router, and outgoing packets must egress through a different router, echo responses will always end up at the ingress router.

You can see this here: https://github.com/Microchip-MPLAB-Harmony/net/blob/2f489a69e9b5ce0dfdaff18f98b3473e9598d5f8/tcpip/src/icmp.c#L648

If properly implemented, the echo response would use the TCPIP_IPV4_SelectSourceInterface() method to select an appropriate route for the packet.

**Comment by adrian-aur** [comment]
Yes, just resending the packet where it came from could create issues in certain network configurations.
We'll create an internal case for this and the fix will be part of the next release.
Thank you for reporting this.

**Comment by adrian-aur** [comment]
The fix is part of net v3.7.2 release
