### ISSUE TITLE
MPFS 3.6.0 erases "HTTP_APP_DYNVAR_BUFFER" in line 177 in http_net_print.h

### ISSUE THREAD

**Issue by manolisss** [Microchip-MPLAB-Harmony/net#35]
Hello,
We are using HTTP_NET (latest library release) for the first time and we set up the example web page to check it out.
Everything was working perfectly until we tried to reproduce the web server source using MPFS 3.6.0 which was included in the latest Harmony 3 files. 
Of course we used the same source files as the template web page files that are provided by Harmony 3.
After that, the build process failed indicating that it couldn't find "HTTP_APP_DYNVAR_BUFFER".
Upon further investigation (restarting the PC and repeating the MPFS process several times, testing on another machine, etc) we came to the conclusion that MPFS 3.6.0 consistently erases "HTTP_APP_DYNVAR_BUFFER" in line 177 of the header file "http_net_print.h", thus causing the build to fail.
 
This piece of code:

```
typedef struct HTTP_APP_DYNVAR_BUFFER
{
    uint16_t busy; // buffer is currently in process
    uint16_t bufferSize; // size of the associated buffer
    char data[HTTP_APP_DYNVAR_BUFFER_SIZE]; // buffer for writing the dynamic variable callback content
}HTTP_APP_DYNVAR_BUFFER;
```

Becomes corrupted after MPFS is run (even with the template web page files):

```
typedef struct 
{
    uint16_t busy; // buffer is currently in process
    uint16_t bufferSize; // size of the associated buffer
    char data[HTTP_APP_DYNVAR_BUFFER_SIZE]; // buffer for writing the dynamic variable callback content
}HTTP_APP_DYNVAR_BUFFER;
```

**Comment by adrian-aur** [comment]
It's been confirmed. It will be fixed ASAP and included in the coming release. Thank you for finding and reporting this.

**Comment by adrian-aur** [comment]
It has been fixed and will be part of the coming release.

**Comment by manolisss** [comment]
Hello @adrian-aur,

Is there any way that you can commit the corrected mpfs_generator files to the [repo ](https://github.com/Microchip-MPLAB-Harmony/net/tree/master/utilities/mpfs_generator)or to put them somewhere temporarily, until the official release of the next net library version? 
It is quite annoying to continually have to re-enter the same text every time a change is made in the webpage.

Thanks in advance,
Manolis

**Comment by adrian-aur** [comment]
Hello @manoliss,
See the attached
[mpfs_net.zip](https://github.com/Microchip-MPLAB-Harmony/net/files/8473334/mpfs_net.zip)
.

**Comment by manolisss** [comment]
> Hello @Manoliss, See the attached [mpfs_net.zip](https://github.com/Microchip-MPLAB-Harmony/net/files/8473334/mpfs_net.zip) .

Thanks, seems to work fine!
