### ISSUE TITLE
Show Heap Size warnings and limitations in MHC TCP/IP CORE GUI

### ISSUE THREAD

**Issue by manolisss** [Microchip-MPLAB-Harmony/net#36]
Hello,

It seems that when using the INTERNAL_HEAP option, the TCP/IP heap is taken from the total project heap. This means that the TCP/IP heap size should be smaller than the project heap size and that there should be a minimum difference between the two. 
A feature should be added in the TCP/IP core GUI module that notes this warning and also that limits the TCP/IP heap size based on the project heap size. It makes no sense that MHC allows you to generate this non-functioning code. 

**Please consider this feature for the next NET package release.**

Manolis

**Comment by adrian-aur** [comment]
The minimum difference between the TCP/IP and project heap is something that depends on the application which may use dynamic allocation or not, or may use other Harmony modules that use dynamic allocation or not, etc. So I do not have a way to exactly quantify that, other than let's say, an arbitrary/hard-coded limit of 2 KB (?) just to be on the safe side.

But the check between the stack and project heap is a valid request and could be done.
I'll create an internal issue for this.
Thank you for your suggestion.

**Comment by manolisss** [comment]
Hello adrian-aur,

Thank you for responding so quickly.

Indeed I realize that this difference depends on the number of enabled Harmony modules, but for sure a minimum hard-coded limit would be a good idea. I assume that even with a minimal amount of Harmony modules active, some KBs would be absolutely necessary to ensure smooth operation. 
I believe that in addition to the check between stack and project heap, the minimum hard-coded limit of a few KBs would also be a good addition.

In any case thank you for your time,
Manolis

**Comment by adrian-aur** [comment]
Sure, no problem.
It will be added to a next release.
