### ISSUE TITLE
GMAC issue PIC32CX

### ISSUE THREAD

**Issue by TheHogfather562** [Microchip-MPLAB-Harmony/net#42]
Hi there,

When adding the GMAC driver into the project, nothing shows up in the project graph. Also the TCP/IP Configuration Window won't open.

Are the PIC32CX not supported yet? I can't see any reference to them in the driver src files https://github.com/Microchip-MPLAB-Harmony/net/tree/master/driver/gmac/src/dynamic

I have attached a simple project to demonstrate the problem.

[GMAC_Test.zip](https://github.com/Microchip-MPLAB-Harmony/net/files/11381322/GMAC_Test.zip)

If it's not yet supported, when will support be available?

Kind regards

**Comment by adrian-aur** [comment]
PIC32CX support is not yet available. We're working on it and we'll release in a few weeks.

**Comment by TheHogfather562** [comment]
Thank you for letting me know! I look forward to the release!

**Comment by TheHogfather562** [comment]
Any news on when this support will be released?

**Comment by adrian-aur** [comment]
The MCC support has been added.
Demo app is under test now.
Probably 2-3 weeks to release.

**Comment by TheHogfather562** [comment]
Any update on this?

**Comment by adrian-aur** [comment]
The release is under way, we're performing the tests. Either the end of this week or the next one.

**Comment by TheHogfather562** [comment]
Has this been released yet?

Also when you said this:

> The MCC support has been added.
> Demo app is under test now.
> Probably 2-3 weeks to release.

Did you mean that it should work now and that you're just developing demo apps for it. Or that it won't work my end still until the demo app is released?

**Comment by adrian-aur** [comment]
Hasn't been released yet. Sorry, sometimes it takes longer than estimated. We'll try to do it as soon as possible.
There will be also demos for PIC32CX.
