### ISSUE TITLE
my application crashes

### ISSUE THREAD

**Issue by picerno76** [Microchip-MPLAB-Harmony/net#44]
I have an application on a WFI3201 that sends UDP packets. I'm using the net package v.3.8 and my application crashes after about 20 seconds when there is no packet sending or if destination address doesn't exist. I have found that it happens because at line 2428 in the file ipv4.c, pHeader is NULL so, if I add a break in this condition, it doesn't crash anymore

**Comment by adrian-aur** [comment]
Sorry for the delay, somehow I've missed your post.
The line #2428 sets the pHeader = pRxPkt->pNetLayer;
On a RX packet, the pNetLayer needs to be set by the MAC driver.
Apparently there's an issue in the Wi-Fi driver.
Please give some more details about the Wi-Fi distribution and application that you use so that I can forward this issue to the corresponding team. A way to reproduce the issue would be nice.

**Comment by picerno76** [comment]
Since I used a WFI3201, the MAC driver should be WDRV_PIC32MZW1, right? To reproduce the issue you must connect to an access point and open a SYS_NET instance without sending messages or sending messages to a not existing destination address in the network. I found out the issue precisely because my UDP server changed its address. I don't remember if it happens without a SYS_NET instance too. I used a mikrotik access point and I don't remember if I tried another one too. After 20 seconds it should crash. Sometime it needs a few more time to happen. thank you

**Comment by adrian-aur** [comment]
OK, I've forwarded your issue to the Wi-Fi team.

**Comment by himanshuseth-microchip** [comment]
Hi,

1. The crash is coming in the RX path in the TCP IP Stack
2. We have run both are UDP Client demo and the UDP Server demo and in both cases, we open a UDP socket, but in neither of the cases we crash even after we have waited for 2 minutes also. 
3. We have sent a packet from a PEER UDP client to the UDP server running on Rio2 with both incorrect and correct ports to see if we experience a crash in RX Flow which is being observed by you, We do not see any. 
4. In the above point, on receiving a packet on the correct port, we even echo back the same packet to the peer UDP client and there is NO crash seen here too.
5. Was any existing Rio2 demo used for creating this application or the application was built from scratch ?
6. Can the you please share your application code for us to check ?

Thanks.

**Comment by picerno76** [comment]
Hi,
I have tried again and as I thought, I have found that it only happens with Mikrotik AP and not with a D-Link AP. This is probably why you don't have the issue. I have seen that pNetLayer is assigned in _TCPIP_PKT_PacketAlloc if segLoadLen > 0. In my case segLoadLen is 0 because in DRV_PIC32MZW_MACEthernetSendPacket lengthEthMsg is 14, so lengthEthMsg-ETHERNET_HDR_LEN == 0. By then, I don't see where DRV_PIC32MZW_MACEthernetSendPacket has been called.
Thank you

**Comment by himanshuseth-microchip** [comment]
Hi,

Could you please raise a Salesforce ticket for this.

Thanks.

**Comment by picerno76** [comment]
Hi,
where do I have to raise a ticket? Do I have to pay for it?
Thank you

**Comment by himanshuseth-microchip** [comment]
Hi,
Sorry for the delayed response.
You can create a login and raise the ticket on https://www.microchip.com/wwwregister/login.aspx?ReturnUrl=https://microchipsupport.force.com
There is no fees.

**Comment by picerno76** [comment]
Hi,
I have raised the ticket but I think I have found the cause of the problem. I don't know if it is a standard method but the mikrotik access point sends a keepalive frame every 20 seconds if the station doesn't send messages to avoid ghost in the registration table. If I disable this feature, the issue doesn't happen anymore. You can read here https://wiki.mikrotik.com/wiki/Manual:Interface/Wireless

**Comment by adrian-aur** [comment]
Well, even if it doesn't happen anymore with the keep-alive disabled, still there is something wrong with these packets, and the crash should not occur.
Probably because of your zero-length packets?
Do you use the TCP/IP stack keep-alive mechanism or you do your own stuff?

**Comment by picerno76** [comment]
it doesn't concern the TCP/IP keep-alive mechanism because it should be at a lower layer, data link or physical
