### ISSUE TITLE
error: flexible array member not at end

### ISSUE THREAD

**Issue by pustekuchen91** [Microchip-MPLAB-Harmony/net#46]
The [macPkt of type TCPIP_MAC_PACKET (== _tag_TCPIP_MAC_PACKET)](https://github.com/Microchip-MPLAB-Harmony/net/blob/a9b589c2782b59341850970a0983379d4441e3f6/tcpip/ipv4.h#L576) which includes a flexible array is not at the end of the struct. So this will fail when using an arm compiler (`arm-none-eabi-g++`) 

```
library/tcpip/tcpip_mac.h:937:37: error: flexible array member '_tag_TCPIP_MAC_PACKET::pktClientLoad' not at end of 'struct<unnamed>'
  937 |     uint32_t                        pktClientLoad[];
```

```
/library/tcpip/ipv4.h:558:22: warning: invalid use of structure with flexible array member [-Wpedantic]
  558 |     TCPIP_MAC_PACKET macPkt; // standard MAC packet header
```

A better solution would be to use an `void *` or `uint32_t *` (dont know the real use of this data) instead of an flexible array.

```c
    /* Additional client packet payload, variable packet data.
       Ignored by the MAC driver. */
    void *pktClientLoad;
```

**Comment by adrian-aur** [comment]
Code has been updated- solved.
