### ISSUE TITLE
Webpage failed to load in demo example web_net_server_nvm_mpfs 

### ISSUE THREAD

**Issue by shiv38237** [Microchip-MPLAB-Harmony/net#49]
I attempted to run the demo example web_net_server_nvm_mpfs using XC32 v4.0 and XC32 v4.21. However, with both toolchains, the webpage fails to load.

Could you please provide a solution to resolve this issue?

**Comment by adrian-aur** [comment]
Please specify what net repo and version you're using.
Does it work with the tools listed in the release notes and the dependencies in the package.xml?
Also, some details: what is it that's not working: just the page load but otherwise the board is alive, you can ping, etc.? Or it is completely dead?

**Comment by shiv38237** [comment]
I am using the following Git repository and version:

Repository: [Microchip MPLAB Harmony Net Apps](https://github.com/Microchip-MPLAB-Harmony/net_apps_pic32cz_ca.git)
Commit ID: a221801f04590c5324d8049456d40a0424e9141e
Branch: master
Tag: v3.10.0
Additionally, I am working with MPLAB X IDE version 6.20.

Please note that the ping functionality is also failing.

Note: Other example in this repo like "tcpip_tcp_client_server" is working and able to ping on IP.

**Comment by shiv38237** [comment]
Please note the following:
In our project, we are using RTOS, so it is essential for the webpage to function correctly on the pic32cz_ca80_curiosity_ultra_freertos.X project.
Currently, this example project is not working, while the pic32cz_ca80_curiosity_ultra.X project is functioning fine.

**Comment by adrian-aur** [comment]
Ok, so to be able to look at it you're saying that the pic32cz_ca80_curiosity_ultra_freertos.X project that is in the v3.10.0 is not working correctly - actually not working at all.
Please confirm.
We'll look into it.

**Comment by shiv38237** [comment]
Yes Correct, it is not working.

**Comment by immfr** [comment]
Hi @shiv38237 

Try doing this, it works for me.

Open MCC and do these settings:

goto TCP/IP configuration in the Plugins drop-down,
1. select Presentation layer, goto its 'RTOS Configuration' and change the 'Task Priority' to **4**
2. select Basic Configuration and select TCPIP Core, goto its 'RTOS configuration' and change the 'Task Priority' to **3**

Then, generate the code, build and program.

After doing these changes,
For me, the webpage started working and it is very quick, flawless & no delay at all. 

Maybe it will work for you, try once and let me know.

**Comment by shiv38237** [comment]
Thank you so much for the suggestion! I made the changes as you described, and it worked perfectly. The webpage is now functioning flawlessly, just as you mentioned—quick and without any delays. I really appreciate your help with this!

Thanks again!

**Comment by immfr** [comment]
I’m glad to hear that it worked for you :)
